name: GuessTheSketch
services:
  main:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"
      - "8001:8001"

  persistance:
    image: "redis/redis-stack:latest"
    ports:
      - "6380:6379"
      - "8002:8001"

  rabbit:
    image: "rabbitmq:4-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: mongo
    restart: always
